"""Generate src/ugr/tables.rs from the eulumdat-ugr Python sources.

The UGR constants (Guth position index, F_GL, F_T, room configurations) are
transferred programmatically so no value is typed by hand. The script only
parses the Python sources with `ast`; numpy and scipy are not needed.

    git clone https://github.com/123VincentB/eulumdat-ugr /tmp/eulumdat-ugr
    python3 tests/fixtures/ugr/reference/generate_tables.py /tmp/eulumdat-ugr

The tables in src/ugr/tables.rs were generated from commit 9f60147.
"""

import ast
import math
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[4]
OUTPUT = REPO_ROOT / "src" / "ugr" / "tables.rs"

GUTH_ROWS = 31
GUTH_COLUMNS = 20
ROOM_COUNT = 19
REFLECTANCE_COUNT = 5


def module_assignments(path: Path) -> dict[str, ast.expr]:
    """Map every (annotated) assignment target in `path` to its value node."""
    tree = ast.parse(path.read_text(encoding="utf-8"))
    nodes = list(tree.body)
    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            nodes.extend(node.body)
    values = {}
    for node in nodes:
        if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            values[node.target.id] = node.value
        elif isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name):
                    values[target.id] = node.value
    return values


def literal(node: ast.expr):
    """Evaluate a literal node, mapping `np.nan` to NaN and `np.array(x, ...)` to x."""
    if isinstance(node, ast.Call) and ast.unparse(node.func) == "np.array":
        return literal(node.args[0])
    if isinstance(node, ast.Attribute) and ast.unparse(node) == "np.nan":
        return math.nan
    if isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.USub):
        return -literal(node.operand)
    if isinstance(node, (ast.List, ast.Tuple)):
        return [literal(element) for element in node.elts]
    if isinstance(node, ast.Dict):
        return {literal(key): literal(value) for key, value in zip(node.keys, node.values)}
    return ast.literal_eval(node)


def number(value: float) -> str:
    if math.isnan(value):
        return "f64::NAN"
    return repr(float(value))


def row(values) -> str:
    return "[" + ", ".join(number(value) for value in values) + "]"


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit("usage: generate_tables.py <path to eulumdat-ugr checkout>")
    package = Path(sys.argv[1]) / "src" / "eulumdat_ugr"

    guth = module_assignments(package / "guth.py")
    table = literal(guth["_TABLE"])
    assert len(table) == GUTH_ROWS and all(len(r) == GUTH_COLUMNS for r in table)
    # The published outlier documented in guth.py and CIE 117:1995.
    assert table[27][6] == 7.50

    background = module_assignments(package / "background.py")
    rooms = literal(background["_ROOM_CONFIGS"])
    room_k = literal(background["_ROOM_K"])
    f_gl = literal(background["_FGL"])
    f_t = literal(background["_FT"])
    reflectances = literal(background["REFLECTANCES"])
    assert len(rooms) == ROOM_COUNT and len(room_k) == ROOM_COUNT
    assert len(reflectances) == REFLECTANCE_COUNT
    assert all(k in f_gl for k in room_k)
    assert all(len(f_t[name]) == ROOM_COUNT for name in reflectances)

    out = []
    out.append("//! UGR constants from CIE 117:1995 and CIE 190:2010.")
    out.append("//!")
    out.append("//! Generated by `tests/fixtures/ugr/reference/generate_tables.py` from the")
    out.append("//! eulumdat-ugr sources (`guth.py`, `background.py`, commit `9f60147`).")
    out.append("//! Do not edit by hand; regenerate instead.")
    out.append("")

    out.append("/// Ceiling, wall, and working-plane reflectances of the UGR table columns.")
    out.append("///")
    out.append("/// Source: CIE 190:2010, column order as in eulumdat-ugr `REFLECTANCES`.")
    out.append(f"pub(crate) const UGR_REFLECTANCES: [(f64, f64, f64); {REFLECTANCE_COUNT}] = [")
    for name in reflectances:
        parts = [int(part) / 100 for part in name.split("/")]
        out.append("    (" + ", ".join(number(part) for part in parts) + "),")
    out.append("];")
    out.append("")

    out.append("/// Room dimensions X × Y as multiples of the mounting height H.")
    out.append("///")
    out.append("/// X is across and Y along the line of sight. Source: CIE 190:2010, room order")
    out.append("/// as in eulumdat-ugr `_ROOM_CONFIGS`.")
    out.append(f"pub(crate) const UGR_ROOMS: [(u8, u8); {ROOM_COUNT}] = [")
    for x, y in rooms:
        out.append(f"    ({int(x)}, {int(y)}),")
    out.append("];")
    out.append("")

    out.append("/// Room index k = X·Y / (H·(X + Y)) of each room in [`UGR_ROOMS`], rounded to")
    out.append("/// two decimals.")
    out.append("///")
    out.append("/// Source: CIE 190:2010 Table 4, as in eulumdat-ugr `_ROOM_K`.")
    out.append(f"pub(crate) const ROOM_K: [f64; {ROOM_COUNT}] = [")
    for k in room_k:
        out.append(f"    {number(k)},")
    out.append("];")
    out.append("")

    out.append("/// Flux-distribution factors `F_GL1` to `F_GL4` per room index k.")
    out.append("///")
    out.append("/// Source: CIE 190:2010 Table 4, as in eulumdat-ugr `_FGL`.")
    out.append(f"pub(crate) const F_GL: [(f64, [f64; 4]); {len(f_gl)}] = [")
    for k, factors in f_gl.items():
        out.append(f"    ({number(k)}, {row(factors)}),")
    out.append("];")
    out.append("")

    out.append("/// Transfer factors (`F_T.FW`, `F_T.WW − 1`, `F_T.CW`) per room and reflectance.")
    out.append("///")
    out.append("/// Indexed as `F_T[room][reflectance]` in the order of [`UGR_ROOMS`] and")
    out.append("/// [`UGR_REFLECTANCES`]. Source: CIE 190:2010 Table 5, as in eulumdat-ugr `_FT`.")
    out.append(f"pub(crate) const F_T: [[[f64; 3]; {REFLECTANCE_COUNT}]; {ROOM_COUNT}] = [")
    for room in range(ROOM_COUNT):
        x, y = rooms[room]
        out.append(f"    // {int(x)}H × {int(y)}H")
        out.append("    [")
        for name in reflectances:
            out.append(f"        {row(f_t[name][room])}, // {name}")
        out.append("    ],")
    out.append("];")
    out.append("")

    out.append("/// Number of Guth table steps per unit of T/R and H/R (axis step 0.1).")
    out.append("pub(crate) const GUTH_STEPS_PER_UNIT: f64 = 10.0;")
    out.append("")
    out.append("/// Guth position index p, indexed as `GUTH_POSITION_INDEX[t_r][h_r]`.")
    out.append("///")
    out.append("/// Rows are T/R = 0.0..=3.0 and columns H/R = 0.0..=1.9, both in steps of")
    out.append("/// 1 / [`GUTH_STEPS_PER_UNIT`]. Cells marked '-' in the standard are `f64::NAN`.")
    out.append("///")
    out.append("/// Source: CIE 117:1995 Table 4.1, as transcribed in eulumdat-ugr `guth.py`.")
    out.append("#[rustfmt::skip]")
    out.append(f"pub(crate) const GUTH_POSITION_INDEX: [[f64; {GUTH_COLUMNS}]; {GUTH_ROWS}] = [")
    out.append("    // T/R \\ H/R" + "  ".join(f"{column / 10:>8.2f}" for column in range(GUTH_COLUMNS)))
    for index, values in enumerate(table):
        if index == 27:
            out.append("    // T/R = 2.70, H/R = 0.60: 7.50 as published in CIE 117:1995.")
        cells = ", ".join(f"{number(value):>8}" for value in values)
        out.append(f"    /* {index / 10:.2f} */ [{cells}],")
    out.append("];")
    out.append("")

    OUTPUT.write_text("\n".join(out), encoding="utf-8")
    subprocess.run(["rustfmt", "--edition", "2024", str(OUTPUT)], check=True)
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
